CREATE TABLE IF NOT EXISTS users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	username varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	active bool DEFAULT false NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_username_key UNIQUE (username),
	CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	description varchar(255),
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT roles_name_key UNIQUE (name),
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
	role_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT users_roles_roles_fk FOREIGN KEY (role_id) REFERENCES roles(id),
	CONSTRAINT users_roles_users_fk FOREIGN KEY (user_id) REFERENCES users(id)	
);